- name: EC2 deployment
  hosts: localhost
  tasks:
  - name: deploying EC2
    ec2:
      key_name: admon
      instance_type: t2.micro
      image: ami-57f0f22b
      wait: yes
      group: default
      count: 1
      region: ap-southeast-1
      vpc_subnet_id: subnet-9b8b82fc
      assign_public_ip: yes
      instance_tags:
        Name: '{{ NameTag }}'
      private_ip: '{{ PrivateIP }}'
